### ISSUE TITLE
Error on /admin

### ISSUE THREAD

**Issue by Berkmann18** [mittalyashu/gridsome-starter-netlifycms#2]
Whenever I try to go to `http://localhost:8080/admin` and click on the link, it leads to this error:
`Error Authenticating with GitHub: You must set a site_id with netlify.configure({site_id: "your-site-id"}) to make authentication work from localhost`.

Here's what I tried (all of which failed) in `config.yml`:
```yaml
backend:
  name: github
  branch: master
  repo: Berkmann18/gridsome-starter-netlifycms
  site_id: compassionate-lalande-822e9b
```

```yaml
backend:
  name: github
  branch: master
  repo: Berkmann18/gridsome-starter-netlifycms

site_id: compassionate-lalande-822e9b`
```
